# Site settings
title: "Layer Zero"
email: 0xalamri@gmail.com
baseurl: ""
url: "http://layer0.xyz"
title_description: "Because there is no such thing as layer zero in the TCP/IP stack layers, I made one which implays the 'strongest' element of that stack (THE USER)."
title_image: "https://thumbs.dreamstime.com/z/manzana-del-ping%C3%BCino-de-la-historieta-y-ejemplo-de-las-ventanas-29538663.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/0xalamri/layer0
addthis_id: ra-513c6fa83da6ec67 
post_limit: 5

# Social usernames/URLs
twitter_username: 0xalamri
github_username:  0xalamri
linkedin_link: https://www.linkedin.com/in/ali-alamri/




# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
